<Project Sdk="MSTest.Sdk/4.3.3">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net47</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cogito.Json.Query\Cogito.Json.Query.csproj" />
    </ItemGroup>

</Project>
